### ISSUE TITLE
CGIを使いながらSqliteのライブラリが使えない

### ISSUE THREAD

**Issue by ikoan08** [Naoki08/science-and-engineering-experiments#3]
```bash
ERROR CGIHandler: lab_search.rb:\n/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- sqlite3 (LoadError)\n\tfrom /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'\n\tfrom lab_search.rb:4:in
```
エラーを読む感じだと、CGIインターフェースを使うと参照してるrubyが違って、そこにsqliteのライブラリが無いと怒られている。

頑張ってPATHとかを通すと多分いけるけど年内に解決するのは力尽きた...

**Comment by minus1208** [comment]
現状、
1.いったんgem uninstall からsqlite3をアンインストール
2.~/.bash_profile に以下を追記
export GEM_HOME=/usr/local/lib/ruby/gems/2.7.0
3. source ~/.bash_profile
4. gem install sqlite3 -v 1.4.0
をすることでエラーを吐かなくなりました

**Comment by minus1208** [comment]
sqlite3のバージョンを下げたことには特に理由がないのでもしかすると最新Verでも動くかもしれません

**Comment by ikoan08** [comment]
パスが通ってる記述のほうが重要そうなのであとで検証します

**Comment by minus1208** [comment]
検証されるとのことなので一応試してうまくいかなかったことと経緯を書いておきます。。
・ruby -I でrequireの行き先をsqlite3のインストール先(gem list sqlite3 -dで見られるやつ）に変えてみる
・requireが参照先として使うパスの一覧$:にsqlite3のインストール先を加えてみる
上記2つはうまくいきませんでした。
最終的にcgi,webrickのインストール先ディレクトリとsqlite3のインストール先ディレクトリが違っているのが原因だと考えました。
なので、
・gemのインストール先(環境変数GEM_HOMEを変更することで変えられるらしい。
参考　https://from-kyushu.hatenadiary.org/entry/20080518/1211118019
）をcgi,webrickのインストール先に変える
・いったんsqlite3を削除して再インストールすることでsqlite3のインストール先をcgi,webrickと同じ場所にする
という処置をとってうまくいったという次第になrます。

**Comment by minus1208** [comment]
activerecordについてもcgiと併用できない問題が発生しているようです。同じ手順で解決できます。
